---
- name: update apt cache
  apt:
    update_cache: yes

- name: upgrade packages
  apt:
    upgrade: dist

- name: remove unnecessary packages
  apt:
    autoremove: true

- name: clean apt cache
  apt:
    autoclean: true
