homelab:
  children:
    edge_nodes:
      hosts:
        svr-edge:
    core_nodes:
      hosts:
        svr-core:
        # svr-host:
        # vm-core:
        # vm-lab:
    cloud_nodes:
      hosts:
        vm-oci:
          ansible_user: ubuntu
